version: '3.1'

services:
    websocket:
        image: php:8.1.2-cli
        volumes:
            - ./websocket:/var/www/html
        ports:
            - "8080:8080"
        command: php /var/www/html/src/chat-server.php
        networks:
            - websockets

    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5555:80'
        env_file:
            - .env
            # - .env.local
        volumes:
            - ./app:/var/www/html
        networks:
            - websockets

    db:
        image: 'mariadb:10.6.4'
        restart: always
        environment:
            # See .env file
            # MYSQL_DATABASE: data
            # MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        env_file:
            - .env
            # - .env.local
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./database/starterDump.sql:/docker-entrypoint-initdb.d/starterDump.sql
        networks:
            - websockets


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '5556:80'
        environment:
            - PMA_ARBITRARY=1
        networks:
            - websockets

networks:
    websockets:
        driver: bridge
